feign:
  httpclient:
    enabled: true
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000  #请求连接超时
        readTimeout: 10000  #请求处理超时
        loggerLevel: none  # full | basic | none | headers
server:
  port: 9001
spring:
  application:
    name: cloud-example-provider
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: 123456
#    url: jdbc:mysql://10.131.124.80:3306/mall-pms?useUnicode=true&useSSL=true&serverTimezone=GMT%2B8
  jackson:
    time-zone: GMT+8
    generator:
      # 避免Long类型丢失经度
      WRITE_NUMBERS_AS_STRINGS: true
  cloud:
    nacos: # 配置nacos
      discovery: # 服务发现地址
        server-addr: 127.0.0.1:8848 # nacos 启动地址
#    sentinel: # 配置sentinel
#      transport:
#        dashboard: 127.0.0.1:8080 # 配置sentinel dashboard 启动地址
#        port: 8719 # 直接写8719 端口号默认是8719 如果被占用就是+1 直到找到未被占用端口
#      filter:
#        url-patterns: /** # 默认是/* 这里改成/** 则会监控所有的请求
#      datasource: # 配置sentinel 流控规则持久化
#        ds1: # 数据库1
#          nacos: # 持久化到 nacos
#            server-addr: 127.0.0.1:8848 # nacos 地址
#            dataId: ${spring.application.name} # 数据id
#            data-type: json # 格式json
#            rule-type: flow # 流控规则
#             namespace: public # 使用默认的 命名空间
#             groupId: DEFAULT_GROUP # 使用默认分组


#zipkin: # 链路追踪
#  base-url: http://localhost:9411
#sleuth:
#  sampler:
#    probability: 1 # 请求抽样百分比 提交到外部的zipkin 1 是100%
#    rate: 100 # 每秒钟最多发送100个请求到zipkin 防止大流量 导致服务压力过大

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.lh.mall.mymall
#mapper:
#  not-empty: false
#  identity: MYSQL
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

management: # 健康检查暴露端点
  endpoints:
    web:
      exposure:
        include: "*"



