server:
  port: 8800
spring:
#  redis:
#    host: 49.232.166.94
#    port: 6379
#    password: QQliuhe951@@
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0
  devtools:
    add-properties: false
  jackson:
    time-zone: GMT+8
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
  application:
    name: cloud-gateway
  cloud:
    #gateway 设置使用服务名路由 默认服务名是大写
    gateway:
      discovery:
        locator:
          enabled: true
          #gateway 服务名小写 (不建议)
#          lower-case-service-id: true
    nacos: # 配置nacos
      discovery: # 服务发现地址
        server-addr: 49.232.166.94:8848 # nacos 启动地址
    sentinel: # 配置sentinel
      transport:
        dashboard: 49.232.166.94:9000 # 配置sentinel dashboard 启动地址
        port: 8719 # 直接写8719 端口号默认是8719 如果被占用就是+1 直到找到未被占用端口
        client-ip: localhost #这个配置时告知sentinel通过哪个ip来ping服务。所以这个ip必须是sentinel所在服务器能ping通的
      filter:
        url-patterns: /** # 默认是/* 这里改成/** 则会监控所有的请求
  zipkin:
    base-url: http://49.232.166.94:9411/ # 服务端地址
    sender:
      type: web # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0 # 收集数据百分比，默认 0.1（10%） 生成中最好不要配置1 影响性能。
# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
