server:
  port: 8800
spring:
  jackson:
    time-zone: GMT+8
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
  application:
    name: cloud-gateway
  cloud:
    #gateway 设置使用服务名路由 默认服务名是大写
    gateway:
      discovery:
        locator:
          enabled: true
          #gateway 服务名小写 (不建议)
#          lower-case-service-id: true
    nacos: # 配置nacos
      discovery: # 服务发现地址
        server-addr: 49.232.166.94:8848 # nacos 启动地址
    sentinel: # 配置sentinel
      transport:
        dashboard: localhost:9000 # 配置sentinel dashboard 启动地址
        port: 8719 # 直接写8719 端口号默认是8719 如果被占用就是+1 直到找到未被占用端口
      filter:
        url-patterns: /** # 默认是/* 这里改成/** 则会监控所有的请求
# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
