feign:
  httpclient:
    enabled: true
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000  #请求连接超时
        readTimeout: 10000  #请求处理超时
        loggerLevel: none  # full | basic | none | headers
  sentinel:
    enabled: true
server:
  port: 9103

spring:
  application:
    name: cloud-example-order
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    time-zone: GMT+8
    generator:
      # 避免Long类型丢失经度
      WRITE_NUMBERS_AS_STRINGS: true
  cloud:
    nacos: # 配置nacos
      discovery: # 服务发现地址
        server-addr: 49.232.166.94:8848 # nacos 启动地址
    sentinel: # 配置sentinel
      transport:
        dashboard: localhost:9000 # 配置sentinel dashboard 启动地址
        port: 8719 # 直接写8719 端口号默认是8719 如果被占用就是+1 直到找到未被占用端口
      filter:
        url-patterns: /** # 默认是/* 这里改成/** 则会监控所有的请求
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 使用多数据源时 这个配置便是 默认数据源
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://49.232.166.94:3306/example-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: QQliuhe951@@
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cloud.base.example.cloud.order.repository.entity
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
management: # 健康检查暴露端点
  endpoints:
    web:
      exposure:
        include: "*"
seata:
  enabled: true
  application-id: cloud-example-order
  tx-service-group: my_test_tx_group
  service:
#    vgroup-mapping.my_test_tx_group: default
    grouplist: { "default": "49.232.166.94:8091" }
