server:
  port: 9300
spring:
  application:
    name: authorize-center-server
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    time-zone: GMT+8
    generator:
      # 避免Long类型丢失经度
      WRITE_NUMBERS_AS_STRINGS: true
  cloud:
    nacos: # 配置nacos
      discovery: # 服务发现地址
        server-addr: 127.0.0.1:8848 # nacos 启动地址
    sentinel: # 配置sentinel
      enabled: true
      transport:
        dashboard: 127.0.0.1:9000 # 配置sentinel dashboard 启动地址
        port: 8719 # 直接写8719 端口号默认是8719 如果被占用就是+1 直到找到未被占用端口
        client-ip: 127.0.0.1 #这个配置时告知sentinel通过哪个ip来ping服务。所以这个ip必须是sentinel所在服务器能ping通的
      filter:
        url-patterns: /** # 默认是/* 这里改成/** 则会监控所有的请求
  zipkin:
    base-url: http://127.0.0.1:9411/ # 服务端地址
    sender:
      type: web # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 0.1 # 收集数据百分比，默认 0.1（10%） 生成中最好不要配置1 影响性能。
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000  #请求连接超时
        readTimeout: 10000  #请求处理超时
        loggerLevel: none  # full | basic | none | headers
  sentinel:
    enabled: true
management: # 健康检查暴露端点
  endpoints:
    web:
      exposure:
        include: "*"
seata:
  enabled: true
  application-id: cloud-example-account
  tx-service-group: my_test_tx_group
  service:
#    vgroup-mapping.my_test_tx_group: default
    grouplist: { "default": "127.0.0.1:8091" }

lhit:
  security:
    server-url-of-check-url: /security/check_url
    server-url-of-check-perms-code: /security/check_perms_code
    server-url-of-check-static-res-path: /security/check_static_res_path
    server-url-of-token-to-authority: /security/token_to_authority

logging:
  level:
    com.alibaba.nacos: error
