server:
  port: 9302
spring:
  application:
    name: merchant-center-server
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    time-zone: GMT+8
    generator:
      # 避免Long类型丢失经度
      WRITE_NUMBERS_AS_STRINGS: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 使用多数据源时 这个配置便是 默认数据源
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://49.232.166.94:3306/member-merchant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: QQliuhe951@@
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  cloud:
    nacos: # 配置nacos
      discovery: # 服务发现地址
        server-addr: 49.232.166.94:8848 # nacos 启动地址
    sentinel: # 配置sentinel
      transport:
        dashboard: 127.0.0.1:9000 # 配置sentinel dashboard 启动地址
        port: 8719 # 直接写8719 端口号默认是8719 如果被占用就是+1 直到找到未被占用端口
        client-ip: localhost #这个配置时告知sentinel通过哪个ip来ping服务。所以这个ip必须是sentinel所在服务器能ping通的
      filter:
        url-patterns: /** # 默认是/* 这里改成/** 则会监控所有的请求
  zipkin:
    base-url: http://49.232.166.94:9411/ # 服务端地址
    sender:
      type: web # 数据传输方式，web 表示以 HTTP 报文的形式向服务端发送数据
  sleuth:
    sampler:
      probability: 1.0 # 收集数据百分比，默认 0.1（10%） 生成中最好不要配置1 影响性能。
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cloud.base.member.merchant.repository.entity
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  redis:
#    host: 49.232.166.94
#    port: 6379
#    password: QQliuhe951@@
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000  #请求连接超时
        readTimeout: 10000  #请求处理超时
        loggerLevel: none  # full | basic | none | headers
  sentinel:
    enabled: true

management: # 健康检查暴露端点
  endpoints:
    web:
      exposure:
        include: "*"
seata:
  enabled: true
  application-id: cloud-example-account
  tx-service-group: my_test_tx_group
  service:
    #    vgroup-mapping.my_test_tx_group: default
    grouplist: { "default": "49.232.166.94:8091" }
