spring:
  cloud:
    nacos: # 配置nacos
      discovery: # 服务发现地址
        server-addr: 127.0.0.1:8848 # nacos 启动地址
      config:
        server-addr: 127.0.0.1:8848 # nacos 启动地址
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/member-user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: liuhe@20211231
youji:
  server:
    heart-beat-corn: 0/5 * * * * ?
    die-no-heart-num: 10
